services:
  modded-tutorial:
    container_name: modded-tutorial
    image: ghcr.io/octoberserver/modded-tutorial:latest
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.modded-tutorial.rule=Host(`tutorials.octsrv.org`)"
      - "traefik.http.routers.modded-tutorial.entrypoints=web,websecure"
networks:
  web:
    external: true
